---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-order-service-deployment
  labels:
    app: nagp-order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nagp-order-service
  template:
    metadata:
      labels:
        app: nagp-order-service
    spec:
      containers:
        - name: nagp-order-service
          image: prateek91sharma/nagp-order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: nagp-order-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer            
 