---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-order-service-deployment
  labels:
    app: nagp-order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nagp-order-service
  template:
    metadata:
      labels:
        app: nagp-order-service
    spec:
      containers:
        - name: nagp-order-service
          image: prateek91sharma/nagp-order-service:latest
          env:
            - name: opentracing.jaeger.udp-sender.host
              value: jaeger-agent 
            - name: opentracing.jaeger.udp-sender.port
              value: "6831"   
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: nagp-order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP    
 